app:
  image: jeromevi/vialfeedmac
  ports:
    - "3000:3000"
  links:
    - mongo
  environment:
    - ROOT_URL=http://localhost:3000
    - MONGO_URL=mongodb://mongo:27017/meteor
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock



mongo:
  image: mongo:latest
  volumes:
    - /Users/swisscom_NG/Desktop/dumpDbMeteor/:/data/seeds
